services:
  postgres:
    image: postgres:latest
    container_name: order-processor-postgres-docker
    restart: unless-stopped
    environment:
      POSTGRES_DB: OrderProcessorDb_Dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_pass_123
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
    ports:
      - '5437:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d OrderProcessorDb_Dev']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - aioutlet-network

  order-processor-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-processor-service-docker
    restart: unless-stopped
    ports:
      - '8083:8083'
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - DB_PASSWORD=postgres_dev_pass_123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/OrderProcessorDb_Dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres_dev_pass_123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=false
      - RABBITMQ_HOST=aioutlet-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - JWT_SECRET=order_processor_jwt_dev_secret_123
      - JWT_ISSUER=aioutlet-auth-service
      - JWT_AUDIENCE=aioutlet-order-processor-service
      - SERVICES_PAYMENT_URL=http://payment-service-docker:80
      - SERVICES_INVENTORY_URL=http://inventory-service-docker:8080
      - SERVICES_SHIPPING_URL=http://shipping-service-docker:80
      - SERVICES_NOTIFICATION_URL=http://notification-service-docker:3008
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - aioutlet-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8083/api/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  aioutlet-network:
    external: true
    name: aioutlet-network
