apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-processor-statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: 'redis_dev_pass_123'
    - name: enableTLS
      value: 'false'
    - name: actorStateStore
      value: 'true'
scopes:
  - order-processor-service
