apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: order-created-subscription
spec:
  topic: order.created
  routes:
    default: /dapr/events/order-created
  pubsubname: event-bus
  deadLetterTopic: order.created.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: payment-processed-subscription
spec:
  topic: payment.processed
  routes:
    default: /dapr/events/payment-processed
  pubsubname: event-bus
  deadLetterTopic: payment.processed.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: payment-failed-subscription
spec:
  topic: payment.failed
  routes:
    default: /dapr/events/payment-failed
  pubsubname: event-bus
  deadLetterTopic: payment.failed.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: inventory-reserved-subscription
spec:
  topic: inventory.reserved
  routes:
    default: /dapr/events/inventory-reserved
  pubsubname: event-bus
  deadLetterTopic: inventory.reserved.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: inventory-failed-subscription
spec:
  topic: inventory.failed
  routes:
    default: /dapr/events/inventory-failed
  pubsubname: event-bus
  deadLetterTopic: inventory.failed.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: shipping-prepared-subscription
spec:
  topic: shipping.prepared
  routes:
    default: /dapr/events/shipping-prepared
  pubsubname: event-bus
  deadLetterTopic: shipping.prepared.deadletter
scopes:
  - order-processor-service
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: shipping-failed-subscription
spec:
  topic: shipping.failed
  routes:
    default: /dapr/events/shipping-failed
  pubsubname: event-bus
  deadLetterTopic: shipping.failed.deadletter
scopes:
  - order-processor-service
